# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test_and_Deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Elixir & Erlang
      uses: erlef/setup-beam@v1.18.2 # v1.16.0
      with:
        elixir-version: '1.15.2' # [Required] Define the Elixir version
        otp-version: '26.0'      # [Required] Define the Erlang/OTP version

    - name: Install Hex & Rebar
      run: |
        mix local.hex --force
        mix local.rebar --force
        
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
        
    - name: Output Elixir & Erlang version
      run: elixir --version
      
    - name: Output PostgreSQL version
      run: psql --version


    # --- PHASE 1: TESTING ---
      
    - name: Install & Compile Dependencies (Test)
      run: |
        mix deps.get
        mix compile
        mix assets.deploy
      env:
        MIX_ENV: test

    - name: Create & migrate database (Test)
      run: |
        mix ecto.create
        mix ecto.migrate
      env:
        MIX_ENV: test
      
    - name: Run tests
      run: mix test
      env:
        MIX_ENV: test

    # --- PHASE 2: BUILDING FOR PRODUCTION ---

    - name: Insall Dependencies (Prod)
      run: |
        mix deps.get --only prod
        mix compile
        mix assets.deploy
        mix phx.gen.release
      env:
        MIX_ENV: prod

    - name: Build Release (Prod)
      run: mix release
      env:
        MIX_ENV: prod

    # --- PHASE 3: DEPLOYING TO VPS ---

    - name: Copy Tar to VPS via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "_build/prod/*.tar.gz"
        target: "~/uploads/RELEASES"
        strip_components: 2
